version: '3.8'

services:
 # --- Servicio Nutshell (Cashu mint) ---
  cashu-mint:
    image: cashubtc/nutshell:0.18.1
    container_name: cashu-mint
    restart: unless-stopped
    volumes:
      - ./cashu/.env:/app/.env
      - ./cashu/data:/app/data
    command: ["poetry", "run", "mint"]
    networks:
      - cashu-network

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      - DB_SQLITE_FILE:"/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      - DISABLE_IPV6:'true'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - cashu-network
      
networks:
  cashu-network:
    driver: bridge